/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__com_snail_gb_GraphicBuffer__H
#define J4A__com_snail_gb_GraphicBuffer__H
#ifdef __cplusplus
extern "C" {
#endif
#include "src/j4a_base.h"

jlong J4AC_com_snail_gb_GraphicBuffer__mNativeObject__get(JNIEnv *env, jobject thiz);
jlong J4AC_com_snail_gb_GraphicBuffer__mNativeObject__get__catchAll(JNIEnv *env, jobject thiz);
void J4AC_com_snail_gb_GraphicBuffer__mNativeObject__set(JNIEnv *env, jobject thiz, jlong value);
void J4AC_com_snail_gb_GraphicBuffer__mNativeObject__set__catchAll(JNIEnv *env, jobject thiz, jlong value);
int J4A_loadClass__J4AC_com_snail_gb_GraphicBuffer(JNIEnv *env);
#ifdef __cplusplus
}
#endif

#endif//J4A__com_snail_gb_GraphicBuffer__H
