/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__android_os_Parcel__H
#define J4A__android_os_Parcel__H
#ifdef __cplusplus
extern "C" {
#endif
#include "src/j4a_base.h"

jobject J4AC_android_os_Parcel__obtain(JNIEnv *env);
jobject J4AC_android_os_Parcel__obtain__catchAll(JNIEnv *env);
jobject J4AC_android_os_Parcel__obtain__asGlobalRef__catchAll(JNIEnv *env);
jint J4AC_android_os_Parcel__readInt(JNIEnv *env, jobject thiz);
jint J4AC_android_os_Parcel__readInt__catchAll(JNIEnv *env, jobject thiz);
void J4AC_android_os_Parcel__setDataPosition(JNIEnv *env, jobject thiz, jint pos);
void J4AC_android_os_Parcel__setDataPosition__catchAll(JNIEnv *env, jobject thiz, jint pos);
jint J4AC_android_os_Parcel__dataSize(JNIEnv *env, jobject thiz);
jint J4AC_android_os_Parcel__dataSize__catchAll(JNIEnv *env, jobject thiz);
jint J4AC_android_os_Parcel__dataAvail(JNIEnv *env, jobject thiz);
jint J4AC_android_os_Parcel__dataAvail__catchAll(JNIEnv *env, jobject thiz);
jint J4AC_android_os_Parcel__dataPosition(JNIEnv *env, jobject thiz);
jint J4AC_android_os_Parcel__dataPosition__catchAll(JNIEnv *env, jobject thiz);
jint J4AC_android_os_Parcel__dataCapacity(JNIEnv *env, jobject thiz);
jint J4AC_android_os_Parcel__dataCapacity__catchAll(JNIEnv *env, jobject thiz);
void J4AC_android_os_Parcel__setDataSize(JNIEnv *env, jobject thiz, jint size);
void J4AC_android_os_Parcel__setDataSize__catchAll(JNIEnv *env, jobject thiz, jint size);
int J4A_loadClass__J4AC_android_os_Parcel(JNIEnv *env);
#ifdef __cplusplus
}
#endif
#endif//J4A__android_os_Parcel__H
