/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#include "j4a_GraphicOnNative.h"

typedef struct J4AC_com_snail_gb_GraphicBuffer {
    jclass id;

    jfieldID field_mNativeObject;
} J4AC_com_snail_gb_GraphicBuffer;
static J4AC_com_snail_gb_GraphicBuffer class_J4AC_com_snail_gb_GraphicBuffer;

jlong J4AC_com_snail_gb_GraphicBuffer__mNativeObject__get(JNIEnv *env, jobject thiz)
{
    return (*env)->GetLongField(env, thiz, class_J4AC_com_snail_gb_GraphicBuffer.field_mNativeObject);
}

jlong J4AC_com_snail_gb_GraphicBuffer__mNativeObject__get__catchAll(JNIEnv *env, jobject thiz)
{
    jlong ret_value = J4AC_com_snail_gb_GraphicBuffer__mNativeObject__get(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

void J4AC_com_snail_gb_GraphicBuffer__mNativeObject__set(JNIEnv *env, jobject thiz, jlong value)
{
    (*env)->SetLongField(env, thiz, class_J4AC_com_snail_gb_GraphicBuffer.field_mNativeObject, value);
}

void J4AC_com_snail_gb_GraphicBuffer__mNativeObject__set__catchAll(JNIEnv *env, jobject thiz, jlong value)
{
    J4AC_com_snail_gb_GraphicBuffer__mNativeObject__set(env, thiz, value);
    J4A_ExceptionCheck__catchAll(env);
}

int J4A_loadClass__J4AC_com_snail_gb_GraphicBuffer(JNIEnv *env)
{
    int         ret                   = -1;
    const char *J4A_UNUSED(name)      = NULL;
    const char *J4A_UNUSED(sign)      = NULL;
    jclass      J4A_UNUSED(class_id)  = NULL;
    int         J4A_UNUSED(api_level) = 0;

    if (class_J4AC_com_snail_gb_GraphicBuffer.id != NULL)
        return 0;

    sign = "com/snail/gb/GraphicBuffer";
    class_J4AC_com_snail_gb_GraphicBuffer.id = J4A_FindClass__asGlobalRef__catchAll(env, sign);
    if (class_J4AC_com_snail_gb_GraphicBuffer.id == NULL)
        goto fail;

    class_id = class_J4AC_com_snail_gb_GraphicBuffer.id;
    name     = "mNativeObject";
    sign     = "J";
    class_J4AC_com_snail_gb_GraphicBuffer.field_mNativeObject = J4A_GetFieldID__catchAll(env, class_id, name, sign);
    if (class_J4AC_com_snail_gb_GraphicBuffer.field_mNativeObject == NULL)
        goto fail;

    J4A_ALOGD("J4ALoader: OK: '%s' loaded\n", "com.snail.gb.GraphicBuffer");
    ret = 0;
fail:
    return ret;
}
