/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#include "GraphicBuffer.h"

typedef struct J4AC_android_view_GraphicBuffer {
    jclass id;

    jfieldID field_mNativeObject;
    jmethodID method_create;
    jmethodID method_writeToParcel;
    jmethodID method_lockCanvas;
    jmethodID method_unlockCanvasAndPost;
} J4AC_android_view_GraphicBuffer;
static J4AC_android_view_GraphicBuffer class_J4AC_android_view_GraphicBuffer;

jlong J4AC_android_view_GraphicBuffer__mNativeObject__get(JNIEnv *env, jobject thiz)
{
    return (*env)->GetLongField(env, thiz, class_J4AC_android_view_GraphicBuffer.field_mNativeObject);
}

jlong J4AC_android_view_GraphicBuffer__mNativeObject__get__catchAll(JNIEnv *env, jobject thiz)
{
    jlong ret_value = J4AC_android_view_GraphicBuffer__mNativeObject__get(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env)) {
        return 0;
    }

    return ret_value;
}

void J4AC_android_view_GraphicBuffer__mNativeObject__set(JNIEnv *env, jobject thiz, jlong value)
{
    (*env)->SetLongField(env, thiz, class_J4AC_android_view_GraphicBuffer.field_mNativeObject, value);
}

void J4AC_android_view_GraphicBuffer__mNativeObject__set__catchAll(JNIEnv *env, jobject thiz, jlong value)
{
    J4AC_android_view_GraphicBuffer__mNativeObject__set(env, thiz, value);
    J4A_ExceptionCheck__catchAll(env);
}

jobject J4AC_android_view_GraphicBuffer__create(JNIEnv *env, jint width, jint height, jint format, jint usage)
{
    return (*env)->CallStaticObjectMethod(env, class_J4AC_android_view_GraphicBuffer.id, class_J4AC_android_view_GraphicBuffer.method_create, width, height, format, usage);
}

jobject J4AC_android_view_GraphicBuffer__create__catchAll(JNIEnv *env, jint width, jint height, jint format, jint usage)
{
    jobject ret_object = J4AC_android_view_GraphicBuffer__create(env, width, height, format, usage);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_android_view_GraphicBuffer__create__asGlobalRef__catchAll(JNIEnv *env, jint width, jint height, jint format, jint usage)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_android_view_GraphicBuffer__create__catchAll(env, width, height, format, usage);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

void J4AC_android_view_GraphicBuffer__writeToParcel(JNIEnv *env, jobject thiz, jobject obj, jint flag)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_android_view_GraphicBuffer.method_writeToParcel, obj, flag);
}

void J4AC_android_view_GraphicBuffer__writeToParcel__catchAll(JNIEnv *env, jobject thiz, jobject obj, jint flag)
{
    J4AC_android_view_GraphicBuffer__writeToParcel(env, thiz, obj, flag);
    J4A_ExceptionCheck__catchAll(env);
}

jobject J4AC_android_view_GraphicBuffer__lockCanvas(JNIEnv *env, jobject thiz)
{
    return (*env)->CallObjectMethod(env, thiz, class_J4AC_android_view_GraphicBuffer.method_lockCanvas);
}

jobject J4AC_android_view_GraphicBuffer__lockCanvas__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object = J4AC_android_view_GraphicBuffer__lockCanvas(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !ret_object) {
        return NULL;
    }

    return ret_object;
}

jobject J4AC_android_view_GraphicBuffer__lockCanvas__asGlobalRef__catchAll(JNIEnv *env, jobject thiz)
{
    jobject ret_object   = NULL;
    jobject local_object = J4AC_android_view_GraphicBuffer__lockCanvas__catchAll(env, thiz);
    if (J4A_ExceptionCheck__catchAll(env) || !local_object) {
        ret_object = NULL;
        goto fail;
    }

    ret_object = J4A_NewGlobalRef__catchAll(env, local_object);
    if (!ret_object) {
        ret_object = NULL;
        goto fail;
    }

fail:
    J4A_DeleteLocalRef__p(env, &local_object);
    return ret_object;
}

void J4AC_android_view_GraphicBuffer__unlockCanvasAndPost(JNIEnv *env, jobject thiz, jobject canvas)
{
    (*env)->CallVoidMethod(env, thiz, class_J4AC_android_view_GraphicBuffer.method_unlockCanvasAndPost, canvas);
}

void J4AC_android_view_GraphicBuffer__unlockCanvasAndPost__catchAll(JNIEnv *env, jobject thiz, jobject canvas)
{
    J4AC_android_view_GraphicBuffer__unlockCanvasAndPost(env, thiz, canvas);
    J4A_ExceptionCheck__catchAll(env);
}

int J4A_loadClass__J4AC_android_view_GraphicBuffer(JNIEnv *env)
{
    int         ret                   = -1;
    const char *J4A_UNUSED(name)      = NULL;
    const char *J4A_UNUSED(sign)      = NULL;
    jclass      J4A_UNUSED(class_id)  = NULL;
    int         J4A_UNUSED(api_level) = 0;

    if (class_J4AC_android_view_GraphicBuffer.id != NULL)
        return 0;

    sign = "android/view/GraphicBuffer";
    class_J4AC_android_view_GraphicBuffer.id = J4A_FindClass__asGlobalRef__catchAll(env, sign);
    if (class_J4AC_android_view_GraphicBuffer.id == NULL)
        goto fail;

    class_id = class_J4AC_android_view_GraphicBuffer.id;
    name     = "mNativeObject";
    sign     = "J";
    class_J4AC_android_view_GraphicBuffer.field_mNativeObject = J4A_GetFieldID__catchAll(env, class_id, name, sign);
    if (class_J4AC_android_view_GraphicBuffer.field_mNativeObject == NULL)
        goto fail;

    class_id = class_J4AC_android_view_GraphicBuffer.id;
    name     = "create";
    sign     = "(IIII)Landroid/view/GraphicBuffer;";
    class_J4AC_android_view_GraphicBuffer.method_create = J4A_GetStaticMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_android_view_GraphicBuffer.method_create == NULL)
        goto fail;

    class_id = class_J4AC_android_view_GraphicBuffer.id;
    name     = "writeToParcel";
    sign     = "(Landroid/os/Parcel;I)V";
    class_J4AC_android_view_GraphicBuffer.method_writeToParcel = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_android_view_GraphicBuffer.method_writeToParcel == NULL)
        goto fail;

    class_id = class_J4AC_android_view_GraphicBuffer.id;
    name     = "lockCanvas";
    sign     = "()Landroid/graphics/Canvas;";
    class_J4AC_android_view_GraphicBuffer.method_lockCanvas = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_android_view_GraphicBuffer.method_lockCanvas == NULL)
        goto fail;

    class_id = class_J4AC_android_view_GraphicBuffer.id;
    name     = "unlockCanvasAndPost";
    sign     = "(Landroid/graphics/Canvas;)V";
    class_J4AC_android_view_GraphicBuffer.method_unlockCanvasAndPost = J4A_GetMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_android_view_GraphicBuffer.method_unlockCanvasAndPost == NULL)
        goto fail;

    J4A_ALOGD("J4ALoader: OK: '%s' loaded\n", "android.view.GraphicBuffer");
    ret = 0;
fail:
    return ret;
}
