/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#ifndef J4A__android_view_GraphicBuffer__H
#define J4A__android_view_GraphicBuffer__H

#include "j4a/j4a_base.h"

jobject J4AC_android_view_GraphicBuffer__create(JNIEnv *env, jint width, jint height, jint format, jint usage);
jobject J4AC_android_view_GraphicBuffer__create__catchAll(JNIEnv *env, jint width, jint height, jint format, jint usage);
jobject J4AC_android_view_GraphicBuffer__create__asGlobalRef__catchAll(JNIEnv *env, jint width, jint height, jint format, jint usage);
void J4AC_android_view_GraphicBuffer__writeToParcel(JNIEnv *env, jobject thiz, jobject obj, jint flag);
void J4AC_android_view_GraphicBuffer__writeToParcel__catchAll(JNIEnv *env, jobject thiz, jobject obj, jint flag);
int J4A_loadClass__J4AC_android_view_GraphicBuffer(JNIEnv *env);

#endif//J4A__android_view_GraphicBuffer__H
